name: 'meta'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"


on-run-start:
  - "{{ meta.log_run_start() }}"


#on-run-end:
#  - "{{ meta.log_run_end() }}"

models:
  meta:
    schema: dbt_meta
