name: 'meta'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"


on-run-start:
  - "{{ meta.create_meta_schema() }}"
  - "{{ meta.create_logging_table() }}"
  - "{{ meta.log_run_start_event() }}"
on-run-end:
  - "{{ meta.log_run_end_event() }}"


models:
  meta:
    schema: meta
